[package]
name = "visitas"
version = "1.0.0"
description = "Contador de visitas"

[fs]
"/" = "."

[[command]]
name = "serve"
module = "sharrattj/php:latest"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-S", "0.0.0.0:8080"]
